# Generated by Django 5.2.10 on 2026-07-06 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner_memberships(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    TeamMember = apps.get_model('teams', 'TeamMember')
    for team in Team.objects.select_related('owner').iterator():
        TeamMember.objects.get_or_create(team=team, user=team.owner)


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'user'), name='unique_team_member')],
            },
        ),
        migrations.RunPython(backfill_owner_memberships, migrations.RunPython.noop),
    ]
