# Generated by Django 5.2.10 on 2026-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_attributes', '0003_siteattributes_s3_custom_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteattributes',
            name='from_email',
            field=models.EmailField(blank=True, help_text='Default from email address for this site', max_length=254),
        ),
    ]
